# Before upgrading check that everything is available on all tier1 targets here:
# https://rust-lang.github.io/rustup-components-history
[toolchain]
channel = "nightly-2023-08-19"
components = ["rust-src", "rustfmt"]
targets = ["thumbv7em-none-eabihf"]
