[package]
name = "nrf-softdevice-gen"
version = "0.1.0"
authors = ["Dario Nieuwenhuis <dirbaio@dirbaio.net>"]
edition = "2021"
license = "MIT OR Apache-2.0"

[dependencies]
bindgen = "0.55.1"
walkdir = "2.3.1"
regex = "1.3.9"
